# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

version: '2'

volumes:
  orderer0.rammiah.org:
  orderer1.rammiah.org:
  orderer2.rammiah.org:
  peer0.org1.rammiah.org:
  peer1.org1.rammiah.org:
  peer2.org1.rammiah.org:
  peer3.org1.rammiah.org:
  peer4.org1.rammiah.org:

networks:
  rbac:

services:

  orderer0.rammiah.org:
    extends:
      file:   base/docker-compose-base.yaml
      service: orderer0.rammiah.org
    container_name: orderer0.rammiah.org
    networks:
      - rbac
  
  orderer1.rammiah.org:
    extends:
      file:   base/docker-compose-base.yaml
      service: orderer1.rammiah.org
    container_name: orderer1.rammiah.org
    networks:
      - rbac
  
  orderer2.rammiah.org:
    extends:
      file:   base/docker-compose-base.yaml
      service: orderer2.rammiah.org
    container_name: orderer2.rammiah.org
    networks:
      - rbac

  peer0.org1.rammiah.org:
    container_name: peer0.org1.rammiah.org
    extends:
      file:  base/docker-compose-base.yaml
      service: peer0.org1.rammiah.org
    networks:
      - rbac

  peer1.org1.rammiah.org:
    container_name: peer1.org1.rammiah.org
    extends:
      file:  base/docker-compose-base.yaml
      service: peer1.org1.rammiah.org
    networks:
      - rbac

  peer2.org1.rammiah.org:
    container_name: peer2.org1.rammiah.org
    extends:
      file:  base/docker-compose-base.yaml
      service: peer2.org1.rammiah.org
    networks:
      - rbac

  peer3.org1.rammiah.org:
    container_name: peer3.org1.rammiah.org
    extends:
      file:  base/docker-compose-base.yaml
      service: peer3.org1.rammiah.org
    networks:
      - rbac
  
  peer4.org1.rammiah.org:
    container_name: peer4.org1.rammiah.org
    extends:
      file:  base/docker-compose-base.yaml
      service: peer4.org1.rammiah.org
    networks:
      - rbac

  cli:
    container_name: cli
    image: hyperledger/fabric-tools:2.0.0
    tty: true
    stdin_open: true
    environment:
      - GOPATH=/opt/gopath
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      #- FABRIC_LOGGING_SPEC=DEBUG
      - FABRIC_LOGGING_SPEC=INFO
      - CORE_PEER_ID=cli
      - CORE_PEER_ADDRESS=peer0.org1.rammiah.org:7051
      - CORE_PEER_LOCALMSPID=Org1MSP
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/opt/gopath/src/peer/crypto/peerOrganizations/org1.rammiah.org/peers/peer0.org1.rammiah.org/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/opt/gopath/src/peer/crypto/peerOrganizations/org1.rammiah.org/peers/peer0.org1.rammiah.org/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/opt/gopath/src/peer/crypto/peerOrganizations/org1.rammiah.org/peers/peer0.org1.rammiah.org/tls/ca.crt
      - CORE_PEER_MSPCONFIGPATH=/opt/gopath/src/peer/crypto/peerOrganizations/org1.rammiah.org/users/Admin@org1.rammiah.org/msp
      - GOPROXY=https://goproxy.cn
    working_dir: /opt/gopath/src/peer
    command: /bin/bash
    volumes:
        - /var/run/:/host/var/run/
        - ./../rbac-contract/:/opt/gopath/src/rbac-contract/
        - ./crypto-config:/opt/gopath/src/peer/crypto/
        - ./scripts:/opt/gopath/src/peer/scripts/
        - ./channel-artifacts:/opt/gopath/src/peer/channel-artifacts
    depends_on:
      - orderer0.rammiah.org
      - orderer1.rammiah.org
      - orderer2.rammiah.org
      - peer0.org1.rammiah.org
      - peer1.org1.rammiah.org
      - peer2.org1.rammiah.org
      - peer3.org1.rammiah.org
      - peer4.org1.rammiah.org
    networks:
      - rbac
